TimeBeforeAfkTrigger: 300000 # The time before the afk player gets a prompt, in milliseconds (default 5 mins / 300000ms)
TimeToUnscramble: 120000 # The time the afk player has to unscramble the word, in ms (default 2 mins / 120000ms)
KickMessage: "You were AFK for too long."

OfferHints: true # Offers hints in case someone really was not afk
LettersRevealedPerHint: 1 # How many letters are revealed in place every hint. Only works if above is true

debug: true # Whether to print debugs in console or not